version: '2'
services:
  mongo:
    image: mongo:4.1-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
    - 27017
    container_name: mongo
  ui:
    build:
      context: ui
    ports:
    - 8080:8080
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: tracing_ui
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
    container_name: ui
    depends_on:
    - mongo
  ads:
    build:
      context: ads
    ports:
    - 8081:8081
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: tracing_ads
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
    container_name: ads
    depends_on:
    - mongo
  ai:
    build:
      context: ai
    expose:
    - 8082
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: tracing_ai
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
    container_name: ai
    depends_on:
    - mongo
  userpref:
    build:
      context: user
    expose:
    - 8083
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: tracing_userpref
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
    container_name: userpref
    depends_on:
    - mongo
